# Site settings
title: 'flock of two, always on the move'
description: Arun and Rashmi on their round the world journey
url: 'enggmind.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Arun'
  email: v.arunindia@gmail.com
  twitter_username: enggmindagain
  facebook_username: kannadiga
  github_username:  enggmind
  linkedin_username:  enggmind

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
